import Head from "next/head";
import { useState } from "react";
import styles from "../../styles/Product.module.css";
import Image from "next/image";
import axios from "axios";
const Product = ({ item, params }) => {
  const [selectedSize, setSelectedSize] = useState(0);
  const [quantity, setQuantity] = useState(1);

  console.log(selectedSize);

  // Price Format
  var nf = new Intl.NumberFormat();

  return (
    <>
      <Head>
        <title>{item ? item?.title : "Ari Shoes"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@500;700;900&display=swap');
          @import
          url('https://fonts.googleapis.com/css2?family=Chivo+Mono:ital,wght@1,700&display=swap');
        </style>
      </Head>

      <div className={styles.container}>
        {/* Left for IMAGE */}
        <div className={styles.left}>
          <div className={styles.imgContainer}>
            <Image src={item?.img} objectFit="contain" layout="fill" alt="" />
          </div>
        </div>
        {/* Right for INFO PRODUCT */}
        <div className={styles.right}>
          <h1 className={styles.title}>{item?.title}</h1>
          {item?.categories.map((categorie) => (
            <h1 className={styles.category} key={categorie}>
              {categorie
                .split(" ")
                .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
                .join("")}
            </h1>
          ))}

          <span className={styles.price}>Rp. {nf.format(item?.price)}</span>
          <p className={styles.desc}>{item?.desc}</p>
          <h3 className={styles.choose}>Select Size</h3>
          <div className={styles.filterContainer}>
            {item?.size.map((size) => (
              <select
                className={size == selectedSize ? styles.active : styles.sizes}
                key={size}
                onClick={(e) => setSelectedSize(e.target.value)}
              >
                <option className={styles.size}>{size}</option>
              </select>
            ))}
          </div>
          {/* Add And Button Cart */}

          <button className={styles.button}>Add to Cart</button>
        </div>
      </div>
    </>
  );
};

export const getServerSideProps = async ({ params }) => {
  const res = await axios.get(
    `http://localhost:3000/api/products/${params.id}`
  );
  return {
    props: {
      item: res.data,
      params: params,
    },
  };
};

export default Product;
