import styles from "@/styles/Products.module.css";
import ItemCard from "@/components/ItemCard";
import axios from "axios";
import Head from "next/head";

const index = ({ products }) => {
  return (
    <>
      <Head>
        <title>Semua Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@500;700;900&display=swap');
          @import
          url('https://fonts.googleapis.com/css2?family=Chivo+Mono:ital,wght@1,700&display=swap');
        </style>
      </Head>
      <div className={styles.container}>
        <h1 className={styles.title}>SEMUA PRODUCTS PILIHAN UNTUK ANDA</h1>
        <div className={styles.Hr} />
        <div className={styles.productWrapper}>
          {products.map((item) => (
            <ItemCard key={item?._id} product={item} />
          ))}
        </div>
      </div>
    </>
  );
};

export const getServerSideProps = async () => {
  const res = await axios.get("http://localhost:3000/api/products");
  return {
    props: {
      products: res.data,
    },
  };
};

export default index;
