import axios from "axios";
import styles from "../../styles/Order.module.css";
import Image from "next/image";
import Head from "next/head";

const Order = ({ order }) => {
  const status = order?.status;

  const statusClass = (index) => {
    if (index - status < 1) return styles.done;
    if (index - status === 1) return styles.inProgress;
    if (index - status > 1) return styles.undone;
  };

  var nf = new Intl.NumberFormat();

  console.log(order);

  return (
    <>
      <Head>
        <title>Order Detail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@500;700;900&display=swap');
          @import
          url('https://fonts.googleapis.com/css2?family=Chivo+Mono:ital,wght@1,700&display=swap');
        </style>
      </Head>
      <div className={styles.container}>
        <div className={styles.left}>
          <div className={styles.row}>
            <table className={styles.table}>
              <tr className={styles.trTitle}>
                <th>Order ID</th>
                <th>Customer</th>
                <th>Address</th>
                <th>Telephone</th>
                <th>Total</th>
              </tr>
              <tr className={styles.tr}>
                <td>
                  <span className={styles.id}>{order?._id.slice(0, 5)}...</span>
                </td>
                <td>
                  <span className={styles.name}>{order?.customer}</span>
                </td>
                <td>
                  <span className={styles.address}>
                    {order?.address.slice(0, 25)}...
                  </span>
                </td>
                <td>
                  <span className={styles.telephone}>0{order?.telephone}</span>
                </td>
                <td>
                  <span className={styles.total}>
                    Rp {nf.format(order?.total)}
                  </span>
                </td>
              </tr>
            </table>
          </div>
          <div className={styles.hr}></div>
          <div className={styles.row}>
            <div className={statusClass(0)}>
              <Image src="/img/paid.png" width={30} height={30} alt="" />
              <span>Payment</span>
              <div className={styles.checkedIcon}>
                <Image
                  className={styles.checkedIcon}
                  src="/img/checked.png"
                  width={20}
                  height={20}
                  alt=""
                />
              </div>
            </div>
            <div className={statusClass(1)}>
              <Image src="/img/packing.png" width={30} height={30} alt="" />
              <span>Preparing</span>
              <div className={styles.checkedIcon}>
                <Image
                  className={styles.checkedIcon}
                  src="/img/checked.png"
                  width={20}
                  height={20}
                  alt=""
                />
              </div>
            </div>
            <div className={statusClass(2)}>
              <Image src="/img/bike.png" width={30} height={30} alt="" />
              <span>On the way</span>
              <div className={styles.checkedIcon}>
                <Image
                  className={styles.checkedIcon}
                  src="/img/checked.png"
                  width={20}
                  height={20}
                  alt=""
                />
              </div>
            </div>
            <div className={statusClass(3)}>
              <Image src="/img/delivered.png" width={30} height={30} alt="" />
              <span>Delivered</span>
              <div className={styles.checkedIcon}>
                <Image
                  className={styles.checkedIcon}
                  src="/img/checked.png"
                  width={20}
                  height={20}
                  alt=""
                />
              </div>
            </div>
          </div>
        </div>
        <div className={styles.right}>
          <div className={styles.wrapper}>
            <h2 className={styles.title}>CART TOTAL</h2>
            <div className={styles.totalText}>
              <b className={styles.totalTextTitle}>Subtotal:</b>{" "}
              {` Rp. ${nf.format(order?.total)} `}
            </div>
            <div className={styles.totalText}>
              <b className={styles.totalTextTitle}>Estimed Delivery:</b>Rp.
              25,000
            </div>
            <div className={styles.totalText}>
              <b className={styles.totalTextTitle}>Total:</b>{" "}
              {` Rp. ${nf.format(order?.total + 25000)} `}
            </div>
            {/* Button */}
            {order?.paid === 0 ? (
              <button disabled className={styles.button}>
                Belum Bayar
              </button>
            ) : (
              <button disabled className={styles.buttonLunas}>
                Lunas
              </button>
            )}
          </div>
        </div>
      </div>
    </>
  );
};

export const getServerSideProps = async ({ params }) => {
  const res = await axios.get(`http://localhost:3000/api/orders/${params.id}`);
  return {
    props: { order: res.data },
  };
};

export default Order;
