import styles from "@/styles/About.module.css";
import Head from "next/head";
const about = () => {
  return (
    <>
      <Head>
        <title>Tentang Kami</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@500;700;900&display=swap');
          @import
          url('https://fonts.googleapis.com/css2?family=Chivo+Mono:ital,wght@1,700&display=swap');
        </style>
      </Head>
      <div className={styles.container}>contact</div>;
    </>
  );
};

export default about;
